token:
  expiration_time: 864000000
  secret: tkdgnsdldmlroqkfdldirltlwkrgkqslektkdgnsdldmlroqkfdldirltlwkrgkqslektkdgnsdldmlroqkfdldirltlwkrgkqslektkdgnsdldmlroqkfdldirltlwkrgkqslekddApplicationChanged2

gateway:
  ip: 192.168.139.1
